const dropdownItems = [
  {
    count: 1,
    id: "mobile-dev",
    title: "برنامه نویسی موبایل",
    courses: [
      "زامارین ( Xamarin )",
      "Kotlin",
      "Ionic",
      "Android",
      "Cordova",
      "PWA",
      "Dart",
      "Flutter",
      "MAUI",
    ],
  },
  {
    count: 2,
    id: "web-dev",
    title: "برنامه نویسی وب",
    courses: [
      "ASP.NET WebForms ",
      "ASP.NET MVC ",
      "PHP ",
      "Asp.Net Core ",
      "Wordpress ",
      "WCF ",
      "Blazor ",
      "Ruby ",
      "GraphQL ",
      "Web GIS ",
      "Django ",
    ],
  },
  {
    count: 3,
    id: "frontend",
    title: "طراحی سایت",
    courses: [
      "Angular ",
      "BootStrap ",
      "طراحی سایت ",
      "React ",
      "Jquery ",
      "JavaScript ",
      "VueJs ",
      "Electron  ",
      "TypeScript GIS  ",
      "FlexBox  ",
      "Sass  ",
      "Composer  ",
      "Stylus  ",
      "Adobe Muse  ",
      "Kendo UI  ",
      "Tailwind CSS  ",
    ],
  },
  {
    count: 4,
    id: "database",
    title: "بانک های اطلاعاتی",
    courses: [
      "SQL Server ",
      "NoSql ",
      "MySql  ",
      "Redis ",
      "Oracle ",
      "Neo4j ",
      "PostgreSQL ",
    ],
  },
  {
    count: 5,
    id: "windows",
    title: "تحت ویندوز",
    courses: [
      "CSharp ",
      "Unity ",
      "NodeJs  ",
      "Python ",
      "Java ",
      "WPF ",
      "Go ",
      "C ",
      "UWP ",
      "DotNet Core ",
      "BlockChain ",
      "Adobe ",
      "مهندسی نرم افزار ",
      "بازی سازی ",
      "Scratch ",
      "Visual Basic ",
      "Matlab ",
      "هوش مصنوعی ",
      "Julia ",
    ],
  },
  { count: 6, id: "seo", title: "سئو" },
  {
    count: 7,
    id: "os",
    title: "سیستم عامل",
    courses: [
      "مدیریت پروژه",
      "Linux",
      "اینترنت ",
      "Docker",
      "ساخت ستاپ",
      "برنامه های کاربردی",
      "Excel",
      "واقعیت افزودن",
      "تولید محتوا",
      "مهارت Core",
      "Security",
      "Network",
      "Word",
    ],
  },
  { count: 8, id: "security", title: "امنیت" },
  {
    count: 9,
    id: "graphic",
    title: "گرافیک",
    courses: [
      "Photoshop  ",
      "گرافیک  ",
      "Premiere   ",
      "موشن گرافیک  ",
      "لوگو  ",
      "Adobe Dreamweave  ",
      "illustrator  ",
      "انیمیشن سازی  ",
      "Cinema 4D  ",
      "Corel Draw  ",
      "3DMax  ",
    ],
  },
];
export default dropdownItems;
